# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://outmanzzq.github.io
date_format: "ordinal"
title: outmanzzq
subtitle: "只管努力，剩下的交给时光。"
description: "outmanzzq的个人博客"
keywords: outmanzzq
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: outmanzzq
organization: 
organization_url: 
github_username: outmanzzq
location: xiamen, China
email: gmoutmanzzq@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: outmanzzq/outmanzzq.github.io

# ---------------- #
#      Comments    #
# ---------------- #
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: outmanzzq
    repo: blog-comments
    clientID: 67f9ad312a98f90cf449
    clientSecret: feeec2658a63a56aa2955a512ed397aeada7dbd5
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-111597454-1
